version: "3"

services:
  ffmpeg:
    build:
      context: ./
      dockerfile: Dockerfile
      shm_size: 2gb
    image: lianshufeng/ffmpeg_chrome
    shm_size: 2gb
    ports:
      - "4444:4444" # selenoid 
      - "8080:8080"
    container_name: ffmpeg
    environment:
      - SCREEN_WIDTH=1920
      - SCREEN_HEIGHT=1080
      - Output_WIDTH=640
      - Output_HEIGHT=360
      - STREAM_URL=rtmp://rtmp.jpy.wang/live/test
    # volumes:
      # - /dev/shm:/dev/shm
    restart: always
    
    
# !!
# curl -X POST http://127.0.0.1:4444/wd/hub/session/$s_id/url -d '{"url":"http://www.baidu.com"}'