version: "3"

services:
  ffmpeg:
    build:
      context: ./
      dockerfile: Dockerfile
      shm_size: 2gb
    image: lianshufeng/ffmpeg_chrome
    shm_size: 2gb
    ports:
      - "4444:4444" # Selenium 
    container_name: ffmpeg
    environment:
      - SE_NODE_SESSION_TIMEOUT=31536000 # 会话过期时间
      - SCREEN_WIDTH=1920
      - SCREEN_HEIGHT=1080
      - Output_WIDTH=640
      - Output_HEIGHT=360
      - STREAM_URL=rtmp://localhost:1935/live/test
    restart: always